services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage   # Persistance locale

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  langserve:
    build: ./api
    container_name: langserve_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - qdrant
      - ollama

volumes:
  qdrant_storage:
  ollama_data:
